global:
  scrape_interval: 5s

rule_files:
- "example.yaml"

scrape_configs:
- job_name: prometheus
  static_configs:
    - targets: ['localhost:9090']
- job_name: currently-app
  static_configs:
    - targets: ['currently-app:8080']
